name: loadingkit_flutter
description: A Flutter Loading Kit Package
version: 0.0.2
repository: https://github.com/slimpotatoboy/loadingkit_flutter
homepage: https://dipenmaharjan.com.np/

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
